#ifndef PARALLELCOMPUTING_PATTERNRECOGNITION_SEQUENTIALRECOGNITION_H
#define PARALLELCOMPUTING_PATTERNRECOGNITION_SEQUENTIALRECOGNITION_H

#include "SAD.h"

MatchResult sequential_recognition(const std::vector<float>& serie, const std::vector<float>& query);

#endif //PARALLELCOMPUTING_PATTERNRECOGNITION_SEQUENTIALRECOGNITION_H